app:
  secretKey: ${SECRET_KEY}
  jwtValidity: ${VALIDITY}

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/${MONGODB_DATABASE}