app:
  secretKey: ${SECRET_KEY}
  jwtValidity: ${VALIDITY}

imagekit:
  urlEndpoint: ${IMAGEKIT_URL_ENDPOINT}
  privateKey: ${IMAGEKIT_PRIVATE_KEY}
  publicKey: ${IMAGEKIT_PUBLIC_KEY}

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/${MONGODB_DATABASE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gokullogan10@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true